FROM alpine:3.8
ENV LAST_UPDATE=20180921
ENV TEMPLATE_ROOT="/srv/"
ENV EXTERNAL_HOSTNAME=""
LABEL authors="Joost van der Griendt <joostvdg@gmail.com>"
LABEL version="0.1.0"
LABEL description="Docker image for CATNIP"
ENTRYPOINT ["catnip"]
COPY index.html /srv/
COPY ./catnip.bin /usr/local/bin/catnip
